[phases.setup]
nixPkgs = ["php83", "composer", "nodejs_20"]

[phases.build]
cmds = [
  "cd backend && composer install --no-dev --optimize-autoloader",
  "cd backend && php artisan config:cache",
  "cd backend && php artisan route:cache",
  "cd backend && php artisan view:cache"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"