[phases.setup]
pkgs = ["php", "phpPackages.composer"]

[phases.build]
cmds = ["cd backend && composer install --no-dev --optimize-autoloader"]

[phases.start]
cmds = ["cd backend && php artisan serve --host=0.0.0.0 --port=8000"]